// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Warranty.Infrastructure.Persistence;

#nullable disable

namespace Warranty.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WarrantyDbContext))]
    [Migration("20261003134628_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Warranty.Domain.Adjudication.AdjudicationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_step");

                    b.Property<string>("Disposition")
                        .HasColumnType("text")
                        .HasColumnName("disposition");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("ReferenceMap")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reference_map");

                    b.Property<int>("Round")
                        .HasColumnType("integer")
                        .HasColumnName("round");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_adjudication_runs");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_adjudication_runs_tenant_id_id");

                    b.HasIndex("ClaimId", "Round")
                        .IsUnique()
                        .HasDatabaseName("ix_adjudication_runs_claim_id_round");

                    b.HasIndex("TenantId", "ClaimId")
                        .HasDatabaseName("ix_adjudication_runs_tenant_id_claim_id");

                    b.ToTable("adjudication_runs", "adjudication");
                });

            modelBuilder.Entity("Warranty.Domain.Adjudication.EvidenceFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<string>("Consistency")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("consistency");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_evidence_findings");

                    b.HasIndex("TenantId", "EvidenceId")
                        .HasDatabaseName("ix_evidence_findings_tenant_id_evidence_id");

                    b.HasIndex("TenantId", "RunId")
                        .HasDatabaseName("ix_evidence_findings_tenant_id_run_id");

                    b.ToTable("evidence_findings", "adjudication");
                });

            modelBuilder.Entity("Warranty.Domain.Adjudication.GuardrailEvaluation", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("ApprovedActionJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("approved_action");

                    b.Property<string>("Checks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("checks");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("disposition");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reasons");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("RunId")
                        .HasName("pk_guardrail_evaluations");

                    b.HasIndex("TenantId", "RunId")
                        .IsUnique()
                        .HasDatabaseName("ix_guardrail_evaluations_tenant_id_run_id");

                    b.ToTable("guardrail_evaluations", "adjudication");
                });

            modelBuilder.Entity("Warranty.Domain.Adjudication.IntakeResult", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("ExtractionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extraction");

                    b.Property<string>("MissingItems")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("missing_items");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Validation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("validation");

                    b.HasKey("RunId")
                        .HasName("pk_intake_results");

                    b.HasIndex("TenantId", "RunId")
                        .IsUnique()
                        .HasDatabaseName("ix_intake_results_tenant_id_run_id");

                    b.ToTable("intake_results", "adjudication");
                });

            modelBuilder.Entity("Warranty.Domain.Adjudication.PolicyAssessment", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("AssessmentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("assessment");

                    b.Property<int?>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prompt_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VersionOutcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_outcome");

                    b.HasKey("RunId")
                        .HasName("pk_policy_assessments");

                    b.HasIndex("TenantId", "RunId")
                        .IsUnique()
                        .HasDatabaseName("ix_policy_assessments_tenant_id_run_id");

                    b.ToTable("policy_assessments", "adjudication");
                });

            modelBuilder.Entity("Warranty.Domain.Adjudication.Recommendation", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("ClaimantExplanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claimant_explanation");

                    b.Property<int?>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<string>("Coverage")
                        .HasColumnType("text")
                        .HasColumnName("coverage");

                    b.Property<string>("Decision")
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<string>("EvidenceRefs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence_refs");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<bool>("ManipulationDetected")
                        .HasColumnType("boolean")
                        .HasColumnName("manipulation_detected");

                    b.Property<string>("MissingInformation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("missing_information");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("PolicyRefs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("policy_refs");

                    b.Property<string>("PromptId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prompt_id");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("RawOutputJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_output");

                    b.Property<string>("ReasoningSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reasoning_summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ValidationErrors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_errors");

                    b.HasKey("RunId")
                        .HasName("pk_recommendations");

                    b.HasIndex("TenantId", "RunId")
                        .IsUnique()
                        .HasDatabaseName("ix_recommendations_tenant_id_run_id");

                    b.ToTable("recommendations", "adjudication");
                });

            modelBuilder.Entity("Warranty.Domain.Adjudication.RetrievedPolicyRef", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Cited")
                        .HasColumnType("boolean")
                        .HasColumnName("cited");

                    b.Property<string>("ClauseKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clause_key");

                    b.Property<string>("ClauseType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clause_type");

                    b.Property<string>("DocumentTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("document_title");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("ExclusionCode")
                        .HasColumnType("text")
                        .HasColumnName("exclusion_code");

                    b.Property<Guid>("KnowledgeChunkId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_chunk_id");

                    b.Property<Guid>("PolicyVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_version_id");

                    b.Property<string>("RefId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ref_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<float>("Score")
                        .HasColumnType("real")
                        .HasColumnName("score");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_retrieved_policy_refs");

                    b.HasIndex("RunId", "RefId")
                        .IsUnique()
                        .HasDatabaseName("ix_retrieved_policy_refs_run_id_ref_id");

                    b.HasIndex("TenantId", "RunId")
                        .HasDatabaseName("ix_retrieved_policy_refs_tenant_id_run_id");

                    b.ToTable("retrieved_policy_refs", "adjudication");
                });

            modelBuilder.Entity("Warranty.Domain.Adjudication.RiskAssessment", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Signals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("signals");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("RunId")
                        .HasName("pk_risk_assessments");

                    b.HasIndex("TenantId", "RunId")
                        .IsUnique()
                        .HasDatabaseName("ix_risk_assessments_tenant_id_run_id");

                    b.ToTable("risk_assessments", "adjudication");
                });

            modelBuilder.Entity("Warranty.Domain.AiOps.ModelCall", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agent");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<int>("CacheReadTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cache_read_tokens");

                    b.Property<int>("CacheWriteTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cache_write_tokens");

                    b.Property<Guid?>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("estimated_cost");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("PromptId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prompt_id");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("route");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StopReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stop_reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_model_calls");

                    b.HasIndex("TenantId", "RunId")
                        .HasDatabaseName("ix_model_calls_tenant_id_run_id");

                    b.ToTable("model_calls", "aiops");
                });

            modelBuilder.Entity("Warranty.Domain.AiOps.RagQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agent");

                    b.Property<string>("FiltersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filters");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.PrimitiveCollection<string[]>("Namespaces")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("namespaces");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_text");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("results");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TopK")
                        .HasColumnType("integer")
                        .HasColumnName("top_k");

                    b.HasKey("Id")
                        .HasName("pk_rag_queries");

                    b.HasIndex("TenantId", "RunId")
                        .HasDatabaseName("ix_rag_queries_tenant_id_run_id");

                    b.ToTable("rag_queries", "aiops");
                });

            modelBuilder.Entity("Warranty.Domain.AiOps.ToolCall", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agent");

                    b.Property<bool>("Allowed")
                        .HasColumnType("boolean")
                        .HasColumnName("allowed");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("arguments");

                    b.Property<string>("DenialReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("denial_reason");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("result_summary");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tool");

                    b.HasKey("Id")
                        .HasName("pk_tool_calls");

                    b.HasIndex("TenantId", "RunId")
                        .HasDatabaseName("ix_tool_calls_tenant_id_run_id");

                    b.ToTable("tool_calls", "aiops");
                });

            modelBuilder.Entity("Warranty.Domain.Audit.DecisionTrailEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("hash");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("PrevHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("prev_hash");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_decision_trail_entries");

                    b.HasIndex("ClaimId", "Seq")
                        .IsUnique()
                        .HasDatabaseName("ix_decision_trail_entries_claim_id_seq");

                    b.HasIndex("TenantId", "ClaimId")
                        .HasDatabaseName("ix_decision_trail_entries_tenant_id_claim_id");

                    b.ToTable("decision_trail_entries", "audit");
                });

            modelBuilder.Entity("Warranty.Domain.Audit.SecurityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("source_ip");

                    b.Property<string>("Target")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("target");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_security_events");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_security_events_tenant_id_occurred_at");

                    b.ToTable("security_events", "audit");
                });

            modelBuilder.Entity("Warranty.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<decimal>("ClaimValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("claim_value");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_products_tenant_id_id");

                    b.HasIndex("TenantId", "ModelCode")
                        .IsUnique()
                        .HasDatabaseName("ix_products_tenant_id_model_code");

                    b.ToTable("products", "catalog");
                });

            modelBuilder.Entity("Warranty.Domain.Catalog.ProductSerial", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("serial_number");

                    b.Property<DateOnly?>("ManufacturedOn")
                        .HasColumnType("date")
                        .HasColumnName("manufactured_on");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("TenantId", "SerialNumber")
                        .HasName("pk_product_serials");

                    b.HasIndex("TenantId", "ProductId")
                        .HasDatabaseName("ix_product_serials_tenant_id_product_id");

                    b.ToTable("product_serials", "catalog");
                });

            modelBuilder.Entity("Warranty.Domain.Claims.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AutoInfoRequestCount")
                        .HasColumnType("integer")
                        .HasColumnName("auto_info_request_count");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateOnly>("ClaimDate")
                        .HasColumnType("date")
                        .HasColumnName("claim_date");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer")
                        .HasColumnName("current_round");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("FinalDecidedBy")
                        .HasColumnType("text")
                        .HasColumnName("final_decided_by");

                    b.Property<string>("FinalExplanation")
                        .HasColumnType("text")
                        .HasColumnName("final_explanation");

                    b.Property<string>("FinalOutcome")
                        .HasColumnType("text")
                        .HasColumnName("final_outcome");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("problem_description");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductModelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("product_model_code");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<string>("PurchasePlace")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("purchase_place");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("purchase_price");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("char(10)")
                        .HasColumnName("reference");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("RequestedItems")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("requested_items");

                    b.Property<bool>("ReviewerInfoRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("reviewer_info_requested");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("submitted_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_claims");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_claims_tenant_id_id");

                    b.HasIndex("TenantId", "CustomerId")
                        .HasDatabaseName("ix_claims_tenant_id_customer_id");

                    b.HasIndex("TenantId", "ProductId")
                        .HasDatabaseName("ix_claims_tenant_id_product_id");

                    b.HasIndex("TenantId", "Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_claims_tenant_id_reference");

                    b.HasIndex("TenantId", "SerialNumber")
                        .HasDatabaseName("ix_claims_tenant_id_serial_number");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_claims_tenant_id_status");

                    b.ToTable("claims", "claims");
                });

            modelBuilder.Entity("Warranty.Domain.Claims.ClaimEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("blob_path");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_name");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("Round")
                        .HasColumnType("integer")
                        .HasColumnName("round");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_claim_evidence");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_claim_evidence_tenant_id_id");

                    b.HasIndex("TenantId", "ClaimId")
                        .HasDatabaseName("ix_claim_evidence_tenant_id_claim_id");

                    b.HasIndex("TenantId", "Sha256")
                        .HasDatabaseName("ix_claim_evidence_tenant_id_sha256");

                    b.ToTable("claim_evidence", "claims");
                });

            modelBuilder.Entity("Warranty.Domain.Claims.ClaimJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<int>("Round")
                        .HasColumnType("integer")
                        .HasColumnName("round");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_claim_jobs");

                    b.HasIndex("ClaimId", "Round")
                        .IsUnique()
                        .HasDatabaseName("ix_claim_jobs_claim_id_round");

                    b.HasIndex("Status", "AvailableAt")
                        .HasDatabaseName("ix_claim_jobs_status_available_at");

                    b.HasIndex("TenantId", "ClaimId")
                        .HasDatabaseName("ix_claim_jobs_tenant_id_claim_id");

                    b.ToTable("claim_jobs", "claims");
                });

            modelBuilder.Entity("Warranty.Domain.Crm.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("country");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_customers_tenant_id_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_tenant_id_email");

                    b.ToTable("customers", "crm");
                });

            modelBuilder.Entity("Warranty.Domain.Integration.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("TenantId", "ClaimId")
                        .HasDatabaseName("ix_notifications_tenant_id_claim_id");

                    b.ToTable("notifications", "integration");
                });

            modelBuilder.Entity("Warranty.Domain.Integration.RepairRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ServiceCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_center_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_repair_requests");

                    b.HasIndex("TenantId", "ClaimId")
                        .HasDatabaseName("ix_repair_requests_tenant_id_claim_id");

                    b.HasIndex("TenantId", "ServiceCenterId")
                        .HasDatabaseName("ix_repair_requests_tenant_id_service_center_id");

                    b.ToTable("repair_requests", "integration");
                });

            modelBuilder.Entity("Warranty.Domain.Integration.ServiceCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Capabilities")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("capabilities");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_service_centers");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_service_centers_tenant_id_id");

                    b.ToTable("service_centers", "integration");
                });

            modelBuilder.Entity("Warranty.Domain.Policies.PolicyClause", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClauseKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clause_key");

                    b.Property<string>("ClauseType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clause_type");

                    b.Property<string>("ExclusionCode")
                        .HasColumnType("text")
                        .HasColumnName("exclusion_code");

                    b.Property<Guid>("PolicyVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_version_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_policy_clauses");

                    b.HasIndex("PolicyVersionId", "ClauseKey")
                        .IsUnique()
                        .HasDatabaseName("ix_policy_clauses_policy_version_id_clause_key");

                    b.HasIndex("TenantId", "PolicyVersionId")
                        .HasDatabaseName("ix_policy_clauses_tenant_id_policy_version_id");

                    b.ToTable("policy_clauses", "policy");
                });

            modelBuilder.Entity("Warranty.Domain.Policies.PolicyVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.PrimitiveCollection<string[]>("ProductCategories")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("product_categories");

                    b.PrimitiveCollection<string[]>("Regions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("regions");

                    b.Property<string>("SourceBlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_blob_path");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("terms");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_policy_versions");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_policy_versions_tenant_id_id");

                    b.HasIndex("PolicyId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_policy_versions_policy_id_version");

                    b.HasIndex("TenantId", "PolicyId")
                        .HasDatabaseName("ix_policy_versions_tenant_id_policy_id");

                    b.ToTable("policy_versions", "policy");
                });

            modelBuilder.Entity("Warranty.Domain.Policies.WarrantyPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_warranty_policies");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_warranty_policies_tenant_id_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_warranty_policies_tenant_id_code");

                    b.ToTable("warranty_policies", "policy");
                });

            modelBuilder.Entity("Warranty.Domain.Review.ReviewDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<string>("ClaimantExplanation")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("claimant_explanation");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<string>("Justification")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("justification");

                    b.Property<bool>("OverridesAi")
                        .HasColumnType("boolean")
                        .HasColumnName("overrides_ai");

                    b.Property<string>("RequestedItems")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("requested_items");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reviewer_name");

                    b.Property<string>("ReviewerSub")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reviewer_sub");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_review_decisions");

                    b.HasIndex("TenantId", "ClaimId")
                        .HasDatabaseName("ix_review_decisions_tenant_id_claim_id");

                    b.HasIndex("TenantId", "RunId")
                        .HasDatabaseName("ix_review_decisions_tenant_id_run_id");

                    b.ToTable("review_decisions", "review");
                });

            modelBuilder.Entity("Warranty.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("character varying(31)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", "tenancy");
                });

            modelBuilder.Entity("Warranty.Domain.Tenancy.TenantChannel", b =>
                {
                    b.Property<string>("Hostname")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("hostname");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Hostname")
                        .HasName("pk_tenant_channels");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_channels_tenant_id");

                    b.ToTable("tenant_channels", "tenancy");
                });

            modelBuilder.Entity("Warranty.Domain.Tenancy.TenantSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.PrimitiveCollection<string[]>("AlwaysReviewCategories")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("always_review_categories");

                    b.Property<decimal>("AutoApprovalLimit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("auto_approval_limit");

                    b.Property<bool>("AutoApproveEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_approve_enabled");

                    b.Property<bool>("AutoRejectEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_reject_enabled");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<int>("MinConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("min_confidence");

                    b.Property<int>("RiskHighThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("risk_high_threshold");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("TenantId")
                        .HasName("pk_tenant_settings");

                    b.ToTable("tenant_settings", "tenancy");
                });

            modelBuilder.Entity("Warranty.Domain.Adjudication.AdjudicationRun", b =>
                {
                    b.HasOne("Warranty.Domain.Claims.Claim", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ClaimId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_adjudication_runs_claims_tenant_id_claim_id");
                });

            modelBuilder.Entity("Warranty.Domain.Adjudication.EvidenceFinding", b =>
                {
                    b.HasOne("Warranty.Domain.Claims.ClaimEvidence", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EvidenceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_evidence_findings_claim_evidence_tenant_id_evidence_id");

                    b.HasOne("Warranty.Domain.Adjudication.AdjudicationRun", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_evidence_findings_adjudication_runs_tenant_id_run_id");
                });

            modelBuilder.Entity("Warranty.Domain.Adjudication.GuardrailEvaluation", b =>
                {
                    b.HasOne("Warranty.Domain.Adjudication.AdjudicationRun", null)
                        .WithOne()
                        .HasForeignKey("Warranty.Domain.Adjudication.GuardrailEvaluation", "TenantId", "RunId")
                        .HasPrincipalKey("Warranty.Domain.Adjudication.AdjudicationRun", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guardrail_evaluations_adjudication_runs_tenant_id_run_id");
                });

            modelBuilder.Entity("Warranty.Domain.Adjudication.IntakeResult", b =>
                {
                    b.HasOne("Warranty.Domain.Adjudication.AdjudicationRun", null)
                        .WithOne()
                        .HasForeignKey("Warranty.Domain.Adjudication.IntakeResult", "TenantId", "RunId")
                        .HasPrincipalKey("Warranty.Domain.Adjudication.AdjudicationRun", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_intake_results_adjudication_runs_tenant_id_run_id");
                });

            modelBuilder.Entity("Warranty.Domain.Adjudication.PolicyAssessment", b =>
                {
                    b.HasOne("Warranty.Domain.Adjudication.AdjudicationRun", null)
                        .WithOne()
                        .HasForeignKey("Warranty.Domain.Adjudication.PolicyAssessment", "TenantId", "RunId")
                        .HasPrincipalKey("Warranty.Domain.Adjudication.AdjudicationRun", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_policy_assessments_adjudication_runs_tenant_id_run_id");
                });

            modelBuilder.Entity("Warranty.Domain.Adjudication.Recommendation", b =>
                {
                    b.HasOne("Warranty.Domain.Adjudication.AdjudicationRun", null)
                        .WithOne()
                        .HasForeignKey("Warranty.Domain.Adjudication.Recommendation", "TenantId", "RunId")
                        .HasPrincipalKey("Warranty.Domain.Adjudication.AdjudicationRun", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recommendations_adjudication_runs_tenant_id_run_id");
                });

            modelBuilder.Entity("Warranty.Domain.Adjudication.RetrievedPolicyRef", b =>
                {
                    b.HasOne("Warranty.Domain.Adjudication.AdjudicationRun", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_retrieved_policy_refs_adjudication_runs_tenant_id_run_id");
                });

            modelBuilder.Entity("Warranty.Domain.Adjudication.RiskAssessment", b =>
                {
                    b.HasOne("Warranty.Domain.Adjudication.AdjudicationRun", null)
                        .WithOne()
                        .HasForeignKey("Warranty.Domain.Adjudication.RiskAssessment", "TenantId", "RunId")
                        .HasPrincipalKey("Warranty.Domain.Adjudication.AdjudicationRun", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_risk_assessments_adjudication_runs_tenant_id_run_id");
                });

            modelBuilder.Entity("Warranty.Domain.AiOps.ModelCall", b =>
                {
                    b.HasOne("Warranty.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_model_calls_tenants_tenant_id");
                });

            modelBuilder.Entity("Warranty.Domain.AiOps.RagQuery", b =>
                {
                    b.HasOne("Warranty.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rag_queries_tenants_tenant_id");
                });

            modelBuilder.Entity("Warranty.Domain.AiOps.ToolCall", b =>
                {
                    b.HasOne("Warranty.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tool_calls_tenants_tenant_id");
                });

            modelBuilder.Entity("Warranty.Domain.Audit.DecisionTrailEntry", b =>
                {
                    b.HasOne("Warranty.Domain.Claims.Claim", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ClaimId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_decision_trail_entries_claims_tenant_id_claim_id");
                });

            modelBuilder.Entity("Warranty.Domain.Audit.SecurityEvent", b =>
                {
                    b.HasOne("Warranty.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_security_events_tenants_tenant_id");
                });

            modelBuilder.Entity("Warranty.Domain.Catalog.Product", b =>
                {
                    b.HasOne("Warranty.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_tenants_tenant_id");
                });

            modelBuilder.Entity("Warranty.Domain.Catalog.ProductSerial", b =>
                {
                    b.HasOne("Warranty.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_serials_products_tenant_id_product_id");
                });

            modelBuilder.Entity("Warranty.Domain.Claims.Claim", b =>
                {
                    b.HasOne("Warranty.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_claims_tenants_tenant_id");

                    b.HasOne("Warranty.Domain.Crm.Customer", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CustomerId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_claims_customers_tenant_id_customer_id");

                    b.HasOne("Warranty.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_claims_products_tenant_id_product_id");
                });

            modelBuilder.Entity("Warranty.Domain.Claims.ClaimEvidence", b =>
                {
                    b.HasOne("Warranty.Domain.Claims.Claim", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ClaimId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_claim_evidence_claims_tenant_id_claim_id");
                });

            modelBuilder.Entity("Warranty.Domain.Claims.ClaimJob", b =>
                {
                    b.HasOne("Warranty.Domain.Claims.Claim", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ClaimId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_claim_jobs_claims_tenant_id_claim_id");
                });

            modelBuilder.Entity("Warranty.Domain.Crm.Customer", b =>
                {
                    b.HasOne("Warranty.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customers_tenants_tenant_id");
                });

            modelBuilder.Entity("Warranty.Domain.Integration.Notification", b =>
                {
                    b.HasOne("Warranty.Domain.Claims.Claim", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ClaimId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_claims_tenant_id_claim_id");
                });

            modelBuilder.Entity("Warranty.Domain.Integration.RepairRequest", b =>
                {
                    b.HasOne("Warranty.Domain.Claims.Claim", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ClaimId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_repair_requests_claims_tenant_id_claim_id");

                    b.HasOne("Warranty.Domain.Integration.ServiceCenter", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ServiceCenterId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_repair_requests_service_centers_tenant_id_service_center_id");
                });

            modelBuilder.Entity("Warranty.Domain.Integration.ServiceCenter", b =>
                {
                    b.HasOne("Warranty.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_centers_tenants_tenant_id");
                });

            modelBuilder.Entity("Warranty.Domain.Policies.PolicyClause", b =>
                {
                    b.HasOne("Warranty.Domain.Policies.PolicyVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PolicyVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_policy_clauses_policy_versions_tenant_id_policy_version_id");
                });

            modelBuilder.Entity("Warranty.Domain.Policies.PolicyVersion", b =>
                {
                    b.HasOne("Warranty.Domain.Policies.WarrantyPolicy", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PolicyId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_policy_versions_warranty_policies_tenant_id_policy_id");
                });

            modelBuilder.Entity("Warranty.Domain.Policies.WarrantyPolicy", b =>
                {
                    b.HasOne("Warranty.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_warranty_policies_tenants_tenant_id");
                });

            modelBuilder.Entity("Warranty.Domain.Review.ReviewDecision", b =>
                {
                    b.HasOne("Warranty.Domain.Claims.Claim", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ClaimId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_review_decisions_claims_tenant_id_claim_id");

                    b.HasOne("Warranty.Domain.Adjudication.AdjudicationRun", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_review_decisions_adjudication_runs_tenant_id_run_id");
                });

            modelBuilder.Entity("Warranty.Domain.Tenancy.TenantChannel", b =>
                {
                    b.HasOne("Warranty.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_channels_tenants_tenant_id");
                });

            modelBuilder.Entity("Warranty.Domain.Tenancy.TenantSettings", b =>
                {
                    b.HasOne("Warranty.Domain.Tenancy.Tenant", null)
                        .WithOne()
                        .HasForeignKey("Warranty.Domain.Tenancy.TenantSettings", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_settings_tenants_tenant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
