/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/public/tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Branding info for the tenant resolved from the Host */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tenant resolved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicTenantInfo"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a claim through the tenant's claimant channel (FR-007) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": components["schemas"]["ClaimSubmissionForm"];
                };
            };
            responses: {
                /** @description Accepted; adjudication runs asynchronously */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionAccepted"];
                    };
                };
                400: components["responses"]["ValidationProblem"];
                413: components["responses"]["Problem"];
                415: components["responses"]["Problem"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/claims/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange claim reference + submitted contact for a claim-scoped token (FR-037a)
         * @description Returns the same 401 for unknown references and non-matching contacts. Failed attempts are recorded as security events. Rate-limited per IP and reference.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClaimantAccessRequest"];
                };
            };
            responses: {
                /** @description Access granted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimantAccessToken"];
                    };
                };
                401: components["responses"]["Problem"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/claims/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Claimant view of a claim (status, outcome explanation, requested items) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reference: components["parameters"]["Reference"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Claim status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimantClaimView"];
                    };
                };
                401: components["responses"]["Problem"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/claims/{reference}/supplements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Supplement a claim that is Pending Information (FR-010) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reference: components["parameters"]["Reference"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": components["schemas"]["SupplementForm"];
                };
            };
            responses: {
                /** @description Accepted; a new evaluation round starts */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionAccepted"];
                    };
                };
                400: components["responses"]["ValidationProblem"];
                401: components["responses"]["Problem"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current staff user (tenant and roles from the token) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                401: components["responses"]["Problem"];
                /** @description The caller's tenant is no longer active */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List claims of the caller's tenant
         * @description Roles claims-agent, claims-reviewer, auditor.
         */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["ClaimStatus"];
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of claims */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimPage"];
                    };
                };
                400: components["responses"]["ValidationProblem"];
            };
        };
        put?: never;
        /**
         * Claims agent submits a claim on a customer's behalf (FR-007)
         * @description Role claims-agent. Tenant comes from the agent's token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": components["schemas"]["ClaimSubmissionForm"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionAccepted"];
                    };
                };
                400: components["responses"]["ValidationProblem"];
                403: components["responses"]["Problem"];
                413: components["responses"]["Problem"];
                415: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/claims/{claimId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full staff view of a claim and its latest evaluation (FR-033)
         * @description Roles claims-agent, claims-reviewer, auditor. For role claims-agent, latestEvaluation.risk, latestEvaluation.recommendation.reasoningSummary, latestEvaluation.guardrails.checks and reviewDecisions[].justification are omitted, and risk-related guardrails.reasons (RISK_MEDIUM, RISK_HIGH, EVIDENCE_CONFLICT, AI_DETERMINISTIC_DISAGREEMENT, UNSAFE_CLAIMANT_TEXT) are replaced by a single "Additional checks required" (FR-005).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    claimId: components["parameters"]["ClaimId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Claim detail */
                200: {
                    headers: {
                        /** @description Row version, required as If-Match for review decisions */
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/claims/{claimId}/supplements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claims agent supplements a Pending Information claim */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    claimId: components["parameters"]["ClaimId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": components["schemas"]["SupplementForm"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionAccepted"];
                    };
                };
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/claims/{claimId}/evidence/{evidenceId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream an evidence file after authorization and tenant check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    claimId: components["parameters"]["ClaimId"];
                    evidenceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": unknown;
                        "image/png": unknown;
                        "image/webp": unknown;
                        "application/pdf": unknown;
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Escalated claims of the reviewer's tenant (FR-032)
         * @description Role claims-reviewer.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Review queue */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewQueueItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/claims/{claimId}/review-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a reviewer decision (FR-034 – FR-036)
         * @description Role claims-reviewer. Allowed only when status is UnderReview. Justification (internal, never shown to the claimant) is required when the decision differs from a valid APPROVE or REJECT recommendation, or is Reject. claimantExplanation is required for Approve and Reject, must be absent for RequestInformation, and becomes the claimant's outcome explanation; it is rejected with 400 when it contains risk/fraud terms or reference IDs (FR-036, FR-037). A RequestInformation decision marks the claim so that, after the supplement, it is re-evaluated and returns to this queue instead of being finalized automatically (FR-034).
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "If-Match": string;
                };
                path: {
                    claimId: components["parameters"]["ClaimId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewDecisionRequest"];
                };
            };
            responses: {
                /** @description Decision recorded; claim updated */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewDecision"];
                    };
                };
                400: components["responses"]["ValidationProblem"];
                /** @description The reviewer submitted this claim and may not decide it (separation of duties); a SELF_REVIEW_REFUSED security event is recorded and nothing changes. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                412: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/claims/{claimId}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chronological decision trail with AI execution steps (FR-038 – FR-041)
         * @description Roles claims-reviewer, auditor.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    claimId: components["parameters"]["ClaimId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Decision trace */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DecisionTrace"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/security-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Security events of the caller's tenant, newest first (FR-041a)
         * @description Role auditor. Returns only events attributed to the caller's tenant; never returns event details or source IP addresses, and never reveals whether a target belongs to another tenant (cross-tenant attempts appear as ACCESS_DENIED, identical to unknown IDs).
         */
        get: {
            parameters: {
                query?: {
                    kind?: components["schemas"]["SecurityEventKind"];
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of security events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SecurityEventPage"];
                    };
                };
                400: components["responses"]["ValidationProblem"];
                403: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policy versions of the caller's tenant (read-only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Policy versions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PolicyVersionSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ClaimStatus: "Submitted" | "UnderEvaluation" | "PendingInformation" | "UnderReview" | "Approved" | "Rejected";
        /** @enum {string} */
        Region: "NA" | "EU";
        /** @enum {string} */
        Disposition: "AutoApprove" | "AutoReject" | "RequestInformation" | "HumanReview";
        /** @enum {string} */
        AiDecision: "APPROVE" | "REJECT" | "REQUEST_MORE_INFORMATION" | "HUMAN_REVIEW";
        /**
         * @description Tenant-visible kinds only; operator-only kinds (CROSS_TENANT_ACCESS_DENIED, UNKNOWN_CHANNEL) are never returned
         * @enum {string}
         */
        SecurityEventKind: "ACCESS_DENIED" | "CLAIMANT_ACCESS_FAILED" | "RETRIEVAL_SCOPE_VIOLATION" | "TOOL_SCOPE_VIOLATION" | "SELF_REVIEW_REFUSED";
        SecurityEvent: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            occurredAt: string;
            kind: components["schemas"]["SecurityEventKind"];
            /** @description Staff display name */
            actor: string;
            /** @description The resource identifier as the actor supplied it */
            target?: string;
        };
        SecurityEventPage: {
            items: components["schemas"]["SecurityEvent"][];
            page: number;
            pageSize: number;
            total: number;
        };
        PublicTenantInfo: {
            displayName: string;
        };
        /** @description Multipart: part `claim` is JSON (application/json). The body contains no tenant field; any tenant-like field is ignored. */
        ClaimSubmissionForm: {
            claim: components["schemas"]["ClaimSubmissionData"];
            /**
             * Format: binary
             * @description PDF or image, max 15 MB
             */
            invoice: string;
            photos: string[];
        };
        ClaimSubmissionData: {
            customer: {
                fullName: string;
                /** Format: email */
                email: string;
                phone?: string;
                addressLine?: string;
                city?: string;
                postalCode?: string;
                country: string;
            };
            product: {
                modelCode: string;
                serialNumber: string;
            };
            purchase: {
                /**
                 * Format: date
                 * @description Not in the future and not after the submission date; otherwise 400 (FR-009)
                 */
                date: string;
                place: string;
                price: number;
                currency: string;
                country: string;
            };
            problemDescription: string;
        };
        SupplementForm: {
            note?: string;
            /** Format: binary */
            invoice?: string;
            photos?: string[];
        };
        SubmissionAccepted: {
            /**
             * Format: uuid
             * @description Staff responses only
             */
            claimId?: string;
            reference: string;
            status: components["schemas"]["ClaimStatus"];
            round: number;
        };
        ClaimantAccessRequest: {
            reference: string;
            /** @description Email address or phone number given at submission */
            contact: string;
        };
        ClaimantAccessToken: {
            accessToken: string;
            /** Format: date-time */
            expiresAt: string;
        };
        /** @description No risk signals, fraud indicators or internal reasoning (FR-037). */
        ClaimantClaimView: {
            reference: string;
            status: components["schemas"]["ClaimStatus"];
            /** Format: date-time */
            submittedAt: string;
            productName?: string;
            /** @description Present when Approved or Rejected: the AI's claimant explanation for automatic decisions, or the reviewer's claimantExplanation for reviewer decisions. Never the reviewer's justification. */
            outcomeExplanation?: string;
            /** @description What the claimant is asked to supply; empty unless Pending Information */
            requestedItems: components["schemas"]["RequestedItem"][];
        };
        RequestedItem: {
            item: string;
            reason: string;
        };
        Me: {
            sub: string;
            name: string;
            tenantDisplayName: string;
            /** @description ISO 4217 code from tenant settings; the currency of every claim value */
            tenantCurrency: string;
            roles: ("claims-agent" | "claims-reviewer" | "auditor")[];
        };
        ClaimSummary: {
            /** Format: uuid */
            claimId: string;
            reference: string;
            status: components["schemas"]["ClaimStatus"];
            productName: string;
            /** Format: date-time */
            submittedAt: string;
            aiDecision?: components["schemas"]["AiDecision"];
            disposition?: components["schemas"]["Disposition"];
        };
        ClaimPage: {
            items: components["schemas"]["ClaimSummary"][];
            page: number;
            pageSize: number;
            total: number;
        };
        /** @description Optional members are omitted from the JSON (never null) when absent or hidden from the caller's role. */
        ClaimDetail: {
            /** Format: uuid */
            claimId: string;
            reference: string;
            status: components["schemas"]["ClaimStatus"];
            /** @enum {string} */
            channel: "ClaimantPortal" | "AgentPortal";
            /** Format: date */
            claimDate: string;
            region?: components["schemas"]["Region"];
            customer: {
                fullName?: string;
                email?: string;
                country?: string;
            };
            /** @description name, category and claimValue only when the product is in the tenant's catalog */
            product: {
                modelCode: string;
                serialNumber: string;
                name?: string;
                category?: string;
                inCatalog: boolean;
                claimValue?: number;
            };
            purchase: {
                /** Format: date */
                date: string;
                place: string;
                price: number;
                /** @description The tenant's currency (ISO 4217) */
                currency: string;
            };
            problemDescription: string;
            evidence: components["schemas"]["EvidenceItem"][];
            latestEvaluation?: components["schemas"]["Evaluation"];
            reviewDecisions: components["schemas"]["ReviewDecision"][];
            /** @enum {string} */
            finalOutcome?: "Approved" | "Rejected";
            /** @enum {string} */
            finalDecidedBy?: "System" | "Reviewer";
            /** @description Claimant-facing explanation shown for the final outcome */
            finalExplanation?: string;
            /** @description Items requested from the claimant by the latest information request (FR-010, FR-029) */
            requestedItems: components["schemas"]["RequestedItem"][];
            /** @description Automatic requests for more information made so far (limit 2, FR-010) */
            autoInfoRequestCount: number;
            /** @description A reviewer has requested more information; later rounds always return to review (FR-034) */
            reviewerInfoRequested: boolean;
        };
        EvidenceItem: {
            /** Format: uuid */
            evidenceId: string;
            /** @description EV-n reference used in the latest evaluation */
            ref?: string;
            /** @enum {string} */
            kind: "Invoice" | "Photo" | "Other";
            fileName: string;
            contentType: string;
            round: number;
        };
        Evaluation: {
            /** Format: uuid */
            runId: string;
            round: number;
            /** @enum {string} */
            status: "Running" | "Completed" | "Failed";
            validation: components["schemas"]["CheckResult"][];
            /** @description intake-extraction.schema.json */
            extraction?: {
                [key: string]: unknown;
            };
            evidenceFindings: components["schemas"]["EvidenceFinding"][];
            policyReferences: components["schemas"]["PolicyReference"][];
            policyAssessment?: components["schemas"]["PolicyAssessment"];
            /** @description Omitted for role claims-agent (FR-005) */
            risk?: {
                score: number;
                /** @enum {string} */
                level: "Low" | "Medium" | "High";
                /**
                 * @description Intake = signals available before evidence analysis (intake short-circuit)
                 * @enum {string}
                 */
                stage: "Intake" | "Full";
                signals: {
                    /** @description Risk signal code, e.g. SOURCE_INCONSISTENCY, DUPLICATE_SERIAL_CLAIM */
                    code: string;
                    /** @enum {string} */
                    source: "Deterministic" | "AI";
                    /** @enum {string} */
                    severity: "Low" | "Medium" | "High";
                    detail: string;
                }[];
            };
            recommendation?: components["schemas"]["Recommendation"];
            guardrails?: {
                disposition: components["schemas"]["Disposition"];
                reasons: string[];
                /** @description Omitted for role claims-agent (FR-005) */
                checks?: components["schemas"]["CheckResult"][];
            };
            failureReason?: string;
        };
        EvidenceFinding: {
            /** @description EV-n reference used in the evaluation */
            ref?: string;
            /** Format: uuid */
            evidenceId: string;
            /** @enum {string} */
            kind: "InvoiceExtraction" | "PhotoAnalysis";
            /** @description invoice-extraction.schema.json or photo-analysis.schema.json */
            result: {
                [key: string]: unknown;
            } | null;
            consistency: components["schemas"]["ConsistencyCheck"][];
            /** @description The Evidence agent's confidence (photo analysis only) */
            confidence?: number;
        };
        /** @description Deterministic cross-check of one field between the claim and a piece of evidence (FR-016) */
        ConsistencyCheck: {
            field: string;
            claimValue: string | null;
            evidenceValue: string | null;
            match: boolean;
        };
        /** @description The Policy agent's reading, the deterministic policy-version selection outcome and the agent's confidence */
        PolicyAssessment: {
            /** @enum {string} */
            versionOutcome: "Ok" | "NoApplicablePolicy" | "AmbiguousPolicyVersion";
            /** @description policy-assessment.schema.json */
            assessment: {
                [key: string]: unknown;
            } | null;
            /** @description The Policy agent's confidence in its coverage assessment */
            confidence?: number;
            model: string;
            promptVersion: string;
        };
        PolicyReference: {
            ref: string;
            clauseKey: string;
            clauseTitle?: string;
            /** @enum {string} */
            clauseType: "Coverage" | "Period" | "Exclusion" | "ServiceRule" | "Definition";
            documentTitle: string;
            version: number;
            /** Format: date */
            effectiveFrom: string;
            /** Format: date */
            effectiveTo: string | null;
            excerpt?: string;
            cited: boolean;
        };
        /** @description An invalid recommendation may lack decision, coverage and confidence. reasoningSummary is omitted for role claims-agent (FR-005); empty texts are omitted. */
        Recommendation: {
            isValid: boolean;
            validationErrors: string[];
            decision?: components["schemas"]["AiDecision"];
            /** @enum {string} */
            coverage?: "COVERED" | "NOT_COVERED" | "UNDETERMINED";
            confidence?: number;
            reasoningSummary?: string;
            claimantExplanation?: string;
            evidenceRefs: {
                ref: string;
                observation: string;
            }[];
            policyRefs: {
                ref: string;
                /** @enum {string} */
                relevance: "SUPPORTS_COVERAGE" | "SUPPORTS_REJECTION" | "DEFINES_PERIOD" | "CONTEXT";
            }[];
            missingInformation: components["schemas"]["RequestedItem"][];
            model: string;
            promptVersion: string;
        };
        CheckResult: {
            code: string;
            stage?: string;
            passed: boolean;
            expected?: string;
            actual?: string;
            message?: string;
        };
        ReviewQueueItem: {
            /** Format: uuid */
            claimId: string;
            reference: string;
            productName: string;
            claimValue?: number;
            aiDecision?: components["schemas"]["AiDecision"];
            confidence?: number;
            /** @enum {string} */
            riskLevel?: "Low" | "Medium" | "High";
            /** Format: date-time */
            escalatedAt: string;
            /** @description The caller submitted this claim and may not decide it (separation of duties) */
            submittedByMe: boolean;
            /** @description Readable labels of the guardrail reason codes (data-model.md), e.g. "returned after reviewer information request" */
            escalationReasons: string[];
        };
        ReviewDecisionRequest: {
            /** @enum {string} */
            decision: "Approve" | "Reject" | "RequestInformation";
            /** @description Internal, staff-only reason; required when overriding the AI or rejecting (FR-035) */
            justification?: string;
            /** @description Required for Approve and Reject, not allowed for RequestInformation. Shown to the claimant as the outcome explanation; must not contain risk or fraud indicators (FR-036). The SPA pre-fills it from the AI's claimantExplanation when the decision matches the AI's. */
            claimantExplanation?: string;
            requestedItems?: components["schemas"]["RequestedItem"][];
        };
        ReviewDecision: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            decision: "Approve" | "Reject" | "RequestInformation";
            justification?: string;
            claimantExplanation?: string;
            requestedItems: components["schemas"]["RequestedItem"][];
            /** @description True only when the decision differs from a valid APPROVE/REJECT recommendation (FR-035) */
            overridesAi: boolean;
            reviewerName: string;
            /** Format: date-time */
            decidedAt: string;
        };
        DecisionTrace: {
            /** Format: uuid */
            claimId: string;
            integrity: {
                hashChainValid?: boolean;
            };
            entries: components["schemas"]["TraceEntry"][];
        };
        /** @description aiCalls, toolCalls and ragQueries are omitted when the step made none. */
        TraceEntry: {
            seq: number;
            /** Format: date-time */
            occurredAt: string;
            /** @description e.g. ClaimSubmitted, PolicyRetrieved, AiRecommended, GuardrailsEvaluated, AutoApproved */
            step: string;
            actor: string;
            summary: string;
            correlationId?: string;
            details?: {
                [key: string]: unknown;
            };
            aiCalls?: components["schemas"]["AiCallSummary"][];
            toolCalls?: {
                agent: string;
                tool: string;
                allowed: boolean;
                latencyMs: number;
                /** @description The stored redacted result or the denial reason */
                summary?: string;
            }[];
            ragQueries?: {
                agent: string;
                namespaces: string[];
                filters: {
                    [key: string]: unknown;
                };
                resultClauseKeys: string[];
                latencyMs: number;
            }[];
        };
        AiCallSummary: {
            agent: string;
            route: string;
            provider: string;
            model: string;
            promptVersion?: string;
            inputTokens: number;
            outputTokens: number;
            cacheReadTokens: number;
            latencyMs: number;
            estimatedCost: number;
            /** @enum {string} */
            status: "Ok" | "Invalid" | "Refused" | "Error" | "Timeout";
            attempt: number;
        };
        PolicyVersionSummary: {
            policyCode: string;
            title: string;
            version: number;
            /** Format: date */
            effectiveFrom: string;
            /** Format: date */
            effectiveTo: string | null;
            regions: components["schemas"]["Region"][];
        };
        ProblemDetails: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            instance?: string;
            correlationId?: string;
        };
        ValidationProblemDetails: components["schemas"]["ProblemDetails"] & {
            errors?: {
                [key: string]: string[];
            };
        };
    };
    responses: {
        /** @description Problem Details */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Validation errors */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblemDetails"];
            };
        };
        /** @description Not found (also returned for other tenants' resources) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description State conflict (e.g. claim not in the required status, concurrent decision) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        ClaimId: string;
        Reference: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
